### ISSUE TITLE
Missing Documentation: Absence of Comments in Code

### ISSUE THREAD

**Issue by Skapupel** [gaitovrat/Clustering#1]
Hello maintainers,

During my recent exploration of the codebase, I noticed a significant absence of in-line documentation, specifically, code comments. As an open-source project, I believe this might create challenges for potential contributors and newcomers to understand the code and its intricacies.

Understanding the intentions behind certain coding decisions and logic can often be challenging when looking at raw code. Well-structured comments can act as essential guides for readers and maintainers. They can explain complex code procedures, clarify the purpose of specific functions or modules, and provide context for decision-making processes.

As such, I'd recommend adding more detailed comments throughout the codebase. This will not only enhance readability and understanding, but will also aid in future debugging and refactoring.

Could we possibly consider adding this to our project's improvement pipeline?

Thanks for your time and consideration.

Best,
Skapupel

**Comment by gaitovrat** [comment]
@Skapupel after our conversation, I did not find out which parts of the code are not clear
